title: Open Source Guide
description: A guide for open source program offices
baseurl: "/oss-guide" # the subpath of your site, e.g. /blog
url: "https://verizonmedia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/OOS_Logo_Mark_Full copy100.png"

# Enable or disable the site search
search_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false/nil
heading_anchors: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright 2019, Verizon Media. Content licensed under CC-BY-4.0"
